
version: '3'
services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: taxi_database
            MYSQL_USER: root
            MYSQL_PASSWORD: 
            
taxidocker:
    build:
        context: /src
    restart: always
    depends_on:
        - mysql
